name: VPS Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: VPS Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            export PATH=/home/ahmedmagdy-vocavault/.nvm/versions/node/v22.23.1/bin:$PATH
            cd /home/ahmedmagdy-vocavault/htdocs/vocavault.ahmedmagdy.cloud
            git fetch origin
            git reset --hard origin/main
            npm ci
            npm run build
            pm2 restart vocavault
